### ISSUE TITLE
Body scale issue

### ISSUE THREAD

**Issue by anime12321** [ManlyMarco/ABMX#14]
What i do:
1.toggle on "xyz scale sliders" option.
2.change the body scale X,Y and Z(Body shape --> overall).
Issue:
it looks like abmx scales the xyz ratio not the chara's body.So when changing different poses like laying or tilting,the chara's body comes out a very odd ratio.

video:https://mega.nz/#!b8oxGCxD!Tl63QpKCO-LCtj7WNVKkwgk6SHfCH8HjXNVuLra8pao

thanks for writing this brillint plugin.

**Comment by ManlyMarco** [comment]
It's a known issue and isn't fixable, at least not easily. This is why the sliders are not split by default.

**Comment by anime12321** [comment]
I get it.Sad to heart that.Thanks.
