### ISSUE TITLE
AI Studio:character disappear when looking her long limbs

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [ManlyMarco/ABMX#15]
I don't know if this a bug?my problem only?but it's really not good.
https://youtu.be/fMPsy8nyRzo
as video shown:
when girl set long legs long arms,and camera focus on feet or hands,she suddenly disappear.
it happened very serious when looking feet
I tested on BepInEx v5 release and BepInEx_x64_b4d5ee5_5.0.0.184
with AI_BepisPlugins_r13.0.1 + AIAPI_1.9.5 + AIABMX_3.5.1
game version is 1.0.4
sorry for bothering

**Comment by ManlyMarco** [comment]
It looks like the game thinks that the character is outside of camera view, and it gets culled. There's probably not much I can do about it without lowering performance of the game. 

It's very rare to have limbs scaled up this much, you're the first person that mentioned this issue. Do you really need to have this work? You could try turning on `forceMatrixRecalculationPerRender` and `updateWhenOffscreen`, maybe also turn off `allowOcclusionWhenDynamic` on the character's renderer by using runtime editor.

**Comment by xiaoxufeiji1a** [comment]
Thank you very much.
This is a good solution for take photo
I just go `CommonSpace/chaF_000/BodyTop/p_cf_body_00/n_o_root/n_body_base/n_body_cf/o_body_cf`
and set `updateWhenOffscreen` `True`
Then it won't disappear anymore,but might need set ct_shoes/ct_socks too.
It's work for me.

But sometimes it shows some window "Sync Top N" "Async Top N" and so much log messages which I can't close them
Thanks support!

**Comment by ManlyMarco** [comment]
Good to hear it worked out! The issue with this fix is that it slows the game down and can cause unity to crash, so I can't really include it in the plugin.

I'm closing the issue since it's unlikely for this to be properly fixed.
