### ISSUE TITLE
[Feature Request] Listing and searching unlisted bones.

### ISSUE THREAD

**Issue by TestSubject173** [ManlyMarco/ABMX#16]
Mainly want this for hairstyle adjustment.

**Comment by ManlyMarco** [comment]
In which game? Did you try advanced window? It will have all available bones. Listing bones will come in future release. In the meantime you can use runtime editor to browse the model structure.

**Comment by TestSubject173** [comment]
> In which game?
AI girl.

> It will have all available bones.
Bones for hairstyle, clothing, and custom face model has to be added manually. But I don't know the names.

> You can use runtime editor to browse the model structure.
Could you elaborate? I'm not a programmer.

**Comment by ManlyMarco** [comment]
Look for chaF object in the runtime editor (F12 or Pause key), the tree under it will have the bone structure of the body and clothes. An update for AI is coming that will make searching for bone names easier in the advanced window.
