### ISSUE TITLE
KK_ABMX not working inside studio

### ISSUE THREAD

**Issue by Tarried** [ManlyMarco/ABMX#21]
As the title says, ABMX settings don't have any effect on characters inside (Koikatu) studio.

I've narrowed down the conflict to KK_Fix_StudioOptimizations. I wasn't sure if I should post this in the IllusionFixes repo, but since you run both projects I don't think it matters.

Using any version of ABMX, and IllusionFixes v1.12, there are no problems, everything works as expected.
With any version of ABMX, and IllusionFixes v13.0 and up, this issue occurs.

This is why BRX5 has this issue, and BRX4 does not.

Hope this helps.

**Comment by ManlyMarco** [comment]
It's fixed in IllusionFixes v13.3
