### ISSUE TITLE
PushUp lost setting effects during animation

### ISSUE THREAD

**Issue by Madevil** [ManlyMarco/ABMX#22]
looks like change in this commit breaks PushUp during animation
https://github.com/ManlyMarco/ABMX/commit/55e32c18da0680b998406f560a3664d1ecfbefef#diff-3b838fb1ed2bc5fd63cae672d09856c4R373-R376

**Comment by ManlyMarco** [comment]
In which game?

**Comment by Madevil** [comment]
in kk, both main game and studio.
it's easier to see the problem if you set breast softness to 0 in PushUp

**Comment by ManlyMarco** [comment]
Should be fixed in latest version.
