### ISSUE TITLE
[HS]About model misalignment

### ISSUE THREAD

**Issue by Hamakaze1s** [ManlyMarco/ABMX#23]
When using ABMX, using Futa model as the male protagonist, part of the action will occur in the wrong place. What can I do?
Using ABMX
[https://i.ibb.co/4R726c4/2.png](url)

Without ABMX
[https://i.ibb.co/9bJcSbj/1.png](url)

**Comment by Hamakaze1s** [comment]
https://i.ibb.co/4R726c4/2.png

https://i.ibb.co/9bJcSbj/1.png

**Comment by ManlyMarco** [comment]
If the card is modified with any ABMX modifiers then it can fail to align in some animations, that's expected.

**Comment by Hamakaze1s** [comment]
Thanks for the reply, I will try to use BetterHscene for manual correction
