### ISSUE TITLE
Advanced ABMX + implanted bones

### ISSUE THREAD

**Issue by dukedickem** [ManlyMarco/ABMX#28]
Found a bug that is very easy to replicate.
1. Set a top with an implanted bone into any coordinate slot that is not the first
2. Change offset and tilt values in advanced ABMX window for said bone
3. Spawn this character in studio
4. When changing to this coordinate the bone will be somewhere inside the character
5. Reloading fixes it somewhat but still doesn't have the correct offset values
6. Only after switching to another coordinate and back again it will have the correctly set values

Here's a webm for demonstration
https://files.catbox.moe/pc1bvs.webm

And here's the card for testing 
https://files.catbox.moe/etnctp.png

**Comment by ManlyMarco** [comment]
Changing implanted bone values is not supported, same with extra accessory and uncensor bones. They aren't filtered out so they can still appear in the advanced window but they will not be loaded properly afterwards and will probably not get saved on next save.

**Comment by dukedickem** [comment]
Allright, good to know.
Saving works fine,  just the loading requires a workaround.
Thanks for the response.

**Comment by ManlyMarco** [comment]
Needs a retest in v5.0

**Comment by ManlyMarco** [comment]
@Alv4rna Can you test if this build fixes the issue? 
[KKABMX.zip](https://github.com/ManlyMarco/ABMX/files/10326609/KKABMX.zip)

**Comment by ManlyMarco** [comment]
Closing as stale, should be fixed by now.
