### ISSUE TITLE
How to enable ABMX in H scene?

### ISSUE THREAD

**Issue by mmqhh** [ManlyMarco/ABMX#29]
The game is HS2. I want to edit the height of the female character in the H scene, I pressed the ABMX enable button, and it said no characters found to edit. How to solve it?

**Comment by ManlyMarco** [comment]
Editing characters in HS2 H scenes is not implemented. Someone has to add HS2-specific logic here https://github.com/ManlyMarco/ABMX/blob/3451987ec9d62ab837a2b49715d2f7ff79ad62c4/Shared/Core/KKABMX_Core.cs#L90

**Comment by mmqhh** [comment]
> Editing characters in HS2 H scenes is not implemented. Someone has to add HS2-specific logic here
> 
> https://github.com/ManlyMarco/ABMX/blob/3451987ec9d62ab837a2b49715d2f7ff79ad62c4/Shared/Core/KKABMX_Core.cs#L90

Alright, can you implement it in the next update? I really need this feature, thanks.

**Comment by ManlyMarco** [comment]
Fixed in v5.0
