### ISSUE TITLE
Swapping Heads Resets to Incorrect Baseline

### ISSUE THREAD

**Issue by OrangeSpork** [ManlyMarco/ABMX#34]
Bug causes character replacement to incorrectly load second character. I believe the issue is that the restore to baseline runs after the head has been replaced, incorrectly restoring the baseline from the first head over the second head and moving custom bones around.

Replication example attached, loading Aloy first loads normally. Loading Miwa (with an obvious eye position mod) and then loading Aloy causes Aloy to load with incorrect eye positions. Should be able to replicate the effect by taking any two heads with a bone position difference, apply a modifier to the first head then load the second and the second will have the first heads baseline position.

Not sure if there's a better solution than to hook before the ChangeHead call and run the reset to baseline before it actually swaps?

![HS2ChaF_20220201231402565](https://user-images.githubusercontent.com/57274555/152104314-ce4f4994-14b1-4341-aa63-0a8941566244.png)
![HS2ChaF_20220201231304772](https://user-images.githubusercontent.com/57274555/152104152-123c04d0-51a0-4b7b-9a4d-fc174537540d.png)

**Comment by BullOnMars** [comment]
Thank you for this awesome fix, Marco.
