### ISSUE TITLE
[HS2] v5 Using some ABMX sliders lock out vanilla sliders

### ISSUE THREAD

**Issue by Kayinnasaki** [ManlyMarco/ABMX#40]
An easy example is changing eyescale and then trying to change eye height, where nothing changes unless you **RE**set the ABMX slider. Double checked that this doesn't happen in v4.

(awesome work by the way, growing pains aside, ABMX5 is so so much nicer to use)

edit: dumb, but misleading typo saying set instead of reset

**Comment by Kayinnasaki** [comment]
I couldn't recreate this in any ways in v4 but I'm not 100% sure what you're asking me to try. I still got v4 in right now so I'd gladly try whatever

**Comment by ManlyMarco** [comment]
Try changing position offset sliders, not only height in v4.

**Comment by Kayinnasaki** [comment]
Even messing with offsets, I couldn't get any sliders, (vanilla or in ambx), to stop working.
