### ISSUE TITLE
[Feature Request] Adding position and rotation adjustments and separating the "bonemod" load option

### ISSUE THREAD

**Issue by OccultOrchard** [ManlyMarco/ABMX#5]
### 1. Adding position and rotation adjustments to advanced bonemod controls

Currently the advanced bonemod controls only include bone scale and length adjustments, which is slightly underwhelming because the "standard" ABMX provides these sliders and already has a great selection of bones.

If it is possible and not too difficult, I think it would be worthwhile to allow the x-y-z position and rotation of each bone to be modified in the advanced mode. Adding these would unlock a lot of potential, since they can create many unique customisations, such as ass horizontal position and spacing. There would be three times as many sliders as what we have now, and the capability of ABMX will be greatly extended.

The KKPE plugin offers these position and rotation adjustments, but they can only be used in the studio and have to be manually entered for each character in each scene. It would be much more natural and convenient if we can just make permanent adjustments using ABMX.

### 2. Separating the "bonemod" load option in character maker

I think the "bonemod" load option at the bottom of the character loading panel in character maker can be separated to "face bonemod" and "body bonemod". Alternatively, this option can be improved to automatically detect what bone adjustments should be loaded i.e. if the "face" load option is selected but not "body", then this "bonemod" option would only load the face bone adjustments. At the moment, a single "bonemod" option makes it difficult to swap faces, because characters can have very different face bone adjustments that go with the vanilla sliders.

Lastly, sorry for the long post and thank you very much for writing such a fantastic plugin. It has become an absolute necessity.

**Comment by ManlyMarco** [comment]
Hello, and thank you for the great suggestions!

1 - It would definitely add a lot more options. I looked into how KKPE does this and it looks like it completely overrides the animations, which is fine in studio where you have full control but will be a problem in the main game and free H. For now I'll put it off until later. I did some research and it might be possible to do this and keep animations happy, but it will require a bunch of work. Also the upcoming release will support negative length sliders so it might be somewhat less necessary.

2 - Added in upcoming release, there are now two separate toggles for face and body.

**Comment by OccultOrchard** [comment]
Thank you for looking into these and adding the separate toggles so quickly. It is too bad that the additional adjustments cannot be added, but your explanation makes sense - I guess that is why similar plugins for earlier Illusion games also did not support position and rotation adjustments.

**Comment by ManlyMarco** [comment]
Work currently ongoing on branch https://github.com/ManlyMarco/ABMX/tree/cym-pr

**Comment by ManlyMarco** [comment]
Implemented in 4.0
