### ISSUE TITLE
KK card's bonemod data from 4.4.6 not reading in V5 or later

### ISSUE THREAD

**Issue by RetroNutcase** [ManlyMarco/ABMX#50]
I've made a lot of cards using 4.4.6, and upgrading to V5 has resulted in a lot of those cards' bone data not loading at all. I've had to roll back to 4.4.6 in order to be able to use these cards as all their bonemods are reverted to base 100 if I load them in v5.

Poke me on discord if you need an example card and I can send you a zipped one, I'm RetroNutcase on there.

For the record, most of the bonemodding I did was via the extra XYZ sliders from things like Chest 2, Lower Body 2, etc.

**Comment by ManlyMarco** [comment]
Make sure you use v5.0.6 and that there are no plugin conflicts. Send your output_log on the server to the help channel.
