### ISSUE TITLE
IllGames HoneyCome

### ISSUE THREAD

**Issue by anonghuser** [ManlyMarco/ABMX#51]
Support the new game of the renamed company.

**Comment by ManlyMarco** [comment]
PRs are welcome.

**Comment by anonghuser** [comment]
I was hoping it's close enough to either KK or HS2 to not need much (any?) changes, however I don't know how to even begin to go about testing that. I tried to look at KKAPI code to see where it gets restricted to certain process, but I only found definition of some proccessname variables that are then not referenced anywhere... Any hints on where I should look to understand the basics?

And on another note, since unlike this mod the KKAPI source is in a repo owned (or at least named after) Illusion's old company name, where do you think the IllGames version should go?

**Comment by ManlyMarco** [comment]
Yes, HC is more similar to RG than to KK.
